document.write('<center><table class="menu">');
document.write('<tr><th  colspan="2"> <a href="./index.html"> HOME</a> </th></tr>');
document.write('<tr><th  colspan="2"> <a href="https://github.com/usqcd-software"> SOFTWARE</a> </th></tr>');
document.write('<tr><th  colspan="2"><a href="./Tutorials.html"> Tutorials </a></th></tr>');
document.write('<tr><th  colspan="2"> <a href="./References.html"> References</a> </th></tr>');
document.write('<tr><th  colspan="2"> <a href="./Impact.html"> Software Impact</a> </th></tr>');
document.write('<tr><th  class="alt" colspan="2"> Applications </th></tr>');
document.write('<tr> ');
document.write('    <td><a href="./Chroma.html">Chroma</a></td>');
document.write('    <td><a href="./MILC.html">MILC</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="./CPS.html">CPS</a></td>');
document.write('    <td><a href="./QLUA.html">QLUA</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="./FUEL.html">FUEL</a></td>');
document.write('</tr>');

document.write('<tr><th  class="alt" colspan="2"> Level 3 libraries </th></tr>');
document.write('<tr>');
document.write('    <td><a href="http://www.mit.edu/~avp/sse/">CG DWF</a></td>');
document.write('    <td><a href=" https://usqcd.lns.mit.edu/redmine/projects/clover">CLOVER</a><br></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="https://usqcd.lns.mit.edu/redmine/projects/mdwf">MDWF</a><br></td>');
document.write('    <td><a href="http://usqcd-software.github.io/qopqdp">QOPQDP</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="http://lattice.github.io/quda/">QUDA</a></td>');
document.write('</tr>');
document.write('<tr><th  class="alt" colspan="2"> Level 2 libraries </th></tr>');
document.write('<tr>');
document.write('    <td><a href="http://usqcd-software.github.io/qdpxx">QDP/C++</a></td>');
document.write('    <td><a href="http://usqcd-software.github.io/qio">QIO</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="http://usqcd-software.github.io/qdp/">QDP/C</a></td>');
document.write('    <td><a href="http://usqcd-software.github.io/c-lime">C-LIME</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="http://usqcd-software.github.io/bagel_qdp/">BAGEL QDP</a></td>');
document.write('</tr>');

document.write('<tr><th  class="alt" colspan="2"> Level 1 libraries </th></tr>');
document.write('<tr>');
document.write('    <td><a href="http://usqcd-software.github.io/qla">QLA</a></td>');
document.write('    <td><a href="http://usqcd-software.github.io/qmp">QMP</a></td>');
document.write('</tr>');
document.write('<tr>');
document.write('    <td><a href="http://usqcd-software.github.io/qmt">QMT</a></td>');
document.write('</tr>');

document.write('<tr><th  colspan="2"> <a href="./MoreSoftware.html"> More Software</a> </th></tr>');
document.write('<tr><th  colspan="2"> <a href="http://qcd.nersc.gov/"> Gauge Connection</a> </th></tr>');
document.write('<tr><th  colspan="2"> <a href="http://www.usqcd.org/computing.html"> Hardware</a> </th></tr>');
document.write('</table></center>');
